# A service call to generate a walking motion
# The request

moveit_msgs/RobotState start_state
moveit_msgs/RobotState goal_state

---

# The returned solution 

moveit_msgs/RobotTrajectory trajectory

moveit_msgs/MoveItErrorCodes error_code
